
# Inspiração
# Repositório Oficial: docker-library/celery
# https://github.com/docker-library/celery
#
# Ajustei o Dockerfile !!!
#
# https://www.blueshoe.io/blog/strategies-for-slim-docker-images
#

FROM rabbitmq:3-management-alpine

RUN apk update 

# Setting para PYTHON
ENV RABBITMQ_ERLANG_COOKIE "SWQOKODSQALRPCLNMEQG"
ENV RABBITMQ_DEFAULT_USER  "owl"
ENV RABBITMQ_DEFAULT_PASS  "owl"

