# docker-compose.yml

version: '3.8'

##----------##      
##  VOLUME  ##
##----------##

# Administração do mapeamento dos volumes utilizados no sistema de microsserviços

services:

  # É recomendavel um diretório exclusivo para volumes. 
  # Isso facilita os backups.

  #--------------------------------------------#
  #  Administração do Banco de Dados PostGres  #
  #--------------------------------------------#

  Admim-PostGreSQL:
    volumes:
      - type: bind
        source: /root/vols/pgadmin
        target: /var/lib/pgadmin
  
  #--------#
  #  MS-1  #
  #--------#

  db-1:
    volumes:
      - type: bind
        source: /root/vols/db-1
        target: /var/lib/postgresql/data               

  #--------#
  #  MS-2  #
  #--------#

  db-2:
    volumes:
      - type: bind
        source: /root/vols/db-2
        target: /var/lib/postgresql/data


