# docker-compose.yml

version: '3.8'

services:

  # Administração do Banco de Dados PostGres
  Admim-PostGreSQL:
    image: dpage/pgadmin4
    container_name: adm
    # automatically restarts the container - Docker daemon on restart or
    # the container itself is manually restarted
    restart: always
    environment:
      # Acesso ao Dashboard de Administração do PostGreSQL
      PGADMIN_DEFAULT_EMAIL: "marcos.antonio.carvalho@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "master"
    ports:
      - "5000:80"



        

